### ISSUE TITLE
keywords won't update after model update/findoneandupdate

### ISSUE THREAD

**Issue by mtzakris** [freakycue/mongoose-search-plugin#5]
What happens if I want to update keywords in a 'PUT' method where I update one document. The setKeywords method updates all the documents of the collection which can be particularly slow. The updateKeywords is a synchronous function which cannot be called with a callback and thus cannot be used. Any ideas?

**Comment by freakycue** [comment]
@mtzakris, It would be quite hard to implement this behaviour for update method, because you can perform partial modifications and keywords could be generated wrong. Instead of update you can fetch object from the db and update it using save method. Another option is to override update/findonupdate with this unsafe behaviour. We may add some special flag for that.
